// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvxu2p8HOy6HMB92DmT2aYIirwu6WED_U',
    appId: '1:858670174942:web:9d24273cacaad6fdf5284f',
    messagingSenderId: '858670174942',
    projectId: 'first-love-church-app',
    authDomain: 'first-love-church-app.firebaseapp.com',
    storageBucket: 'first-love-church-app.firebasestorage.app',
    measurementId: 'G-LYQKH9KD1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:',
    messagingSenderId: '858670174942',
    projectId: 'first-love-church-app',
    storageBucket: 'first-love-church-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:',
    messagingSenderId: '858670174942',
    projectId: 'first-love-church-app',
    storageBucket: 'first-love-church-app.firebasestorage.app',
    iosBundleId: 'com.example.flcms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt-UYnWX6UxsOP-utGVOQ-Ay73awyebLc',
    appId: '1:858670174942:ios:5e7406601e46eca9f5284f',
    messagingSenderId: '858670174942',
    projectId: 'first-love-church-app',
    storageBucket: 'first-love-church-app.firebasestorage.app',
    iosBundleId: 'com.example.flcms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:858670174942:web:653da14f55e39d15f5284f',
    messagingSenderId: '858670174942',
    projectId: 'first-love-church-app',
    authDomain: 'first-love-church-app.firebaseapp.com',
    storageBucket: 'first-love-church-app.firebasestorage.app',
    measurementId: 'G-3ENFVK52E1',
  );

}
